word = [
        "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
        "kiwi", "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry",
        "strawberry", "tangerine", "watermelon", "zebra", "elephant", "giraffe", "hippopotamus",
        "iguana", "jaguar", "kangaroo", "lion", "monkey", "newt", "octopus", "penguin",
        "quail", "rhinoceros", "snake", "tiger", "unicorn", "vulture", "walrus", "xray",
        "yak", "ant", "bear", "cat", "dog", "eel", "fox", "goat", "hen", "impala", "jay",
        "koala", "llama", "mouse", "narwhal", "owl", "pig", "raven", "sheep", "toad",
        "urchin", "viper", "weasel", "yeti", "bee", "cow", "dove", "frog", "hawk", "mole",
        "puma", "seal", "wasp", "almond", "bread", "carrot", "donut", "eggplant", "fries",
        "grapes", "honey", "icecream", "juice", "kale", "lime", "muffin", "noodles",
        "olive", "pasta", "quinoa", "rice", "salad", "toast", "umbrella", "violet",
        "window", "xylophone", "yacht", "zipper", "computer", "keyboard", "monitor", "software",
        "network", "internet", "programming", "algorithm", "database", "function", "variable"
    ]

hangman_words = {
    "apple": "A round fruit with red or green skin.",
    "banana": "A long, curved yellow fruit.",
    "cherry": "A small, round, red fruit with a pit.",
    "grape": "A small, round or oval fruit that grows in clusters.",
    "orange": "A citrus fruit with a thick, orange peel.",
    "strawberry": "A red, heart-shaped fruit with small seeds.",
    "elephant": "A large mammal with a trunk.",
    "giraffe": "A tall animal with a long neck.",
    "kangaroo": "An Australian marsupial that hops.",
    "penguin": "A flightless bird that lives in cold climates.",
    "butterfly": "An insect with colorful wings.",
    "computer": "An electronic device for storing and processing data.",
    "keyboard": "An input device with keys.",
    "monitor": "A display screen for a computer.",
    "printer": "A device that produces printed copies.",
    "python": "A popular programming language.",
    "summer": "The warmest season of the year.",
    "winter": "The coldest season of the year.",
    "spring": "The season of growth and renewal.",
    "autumn": "The season of falling leaves.",
    "ocean": "A large body of saltwater.",
    "mountain": "A large natural elevation of the earth's surface.",
    "river": "A large natural stream of water flowing in a channel.",
    "forest": "A large area covered with trees.",
    "desert": "A dry, barren area of land with little or no vegetation.",
    "house": "A building for human habitation.",
    "garden": "A plot of land used for growing flowers, vegetables, or fruit.",
    "school": "An institution for educating children.",
    "hospital": "An institution providing medical or surgical treatment.",
    "library": "A building or room containing collections of books.",
    "cinema": "A place where films are shown.",
    "football": "A team sport played with a spherical ball.",
    "basketball": "A team sport played with a ball and hoop.",
    "tennis": "A racket sport played with a ball and net.",
    "swimming": "The sport or activity of propelling oneself through water.",
    "running": "The activity of moving rapidly on foot.",
    "painting": "The process or art of using paint.",
    "singing": "The activity of making musical sounds with the voice.",
    "dancing": "Moving rhythmically to music.",
    "reading": "The activity of looking at and comprehending written words.",
    "writing": "The activity of composing text.",
    "coffee": "A hot drink made from roasted and ground coffee beans.",
    "tea": "A hot drink made by infusing dried leaves in hot water.",
    "water": "A colorless, transparent, odorless liquid.",
    "bread": "Food made of flour, water, and yeast or other leavening agent.",
    "cheese": "A food made from coagulated milk.",
    "chicken": "A domestic fowl bred for its flesh or eggs.",
    "rabbit": "A burrowing, gregarious mammal with long ears, long hind legs, and a short tail.",
    "turtle": "A slow-moving reptile with a bony shell.",
    "dragon": "A mythical monster with wings and fire-breathing abilities.",
    "castle": "A large building or group of buildings fortified against attack.",
    "island": "A piece of land surrounded by water.",
    "planet": "A celestial body moving in an elliptical orbit around a star.",
    "rocket": "A vehicle propelled by a rocket engine.",
    "telescope": "An optical instrument designed to make distant objects appear nearer.",
    "microscope": "An optical instrument used for viewing very small objects.",
    "camera": "A device for recording visual images in the form of photographs, film, or video signals.",
    "telephone": "A system for transmitting voices over distances.",
    "bicycle": "A vehicle with two wheels in tandem, propelled by pedals.",
    "airplane": "A powered flying vehicle with fixed wings and a weight greater than that of the air it displaces.",
    "train": "A series of railway carriages or wagons moved by a locomotive.",
    "ship": "A large boat or vessel carrying passengers or cargo.",
    "clock": "An instrument for measuring and indicating time.",
    "mirror": "A reflective surface, now typically of glass backed with a metal amalgam.",
    "candle": "A cylindrical or tapered mass of wax or tallow with a wick that is burned to provide light.",
    "pillow": "A cushion used to support the head, especially during sleep.",
    "blanket": "A large piece of woolen or other woven fabric used as a covering to keep one warm.",
    "window": "An opening in the wall or roof of a building or vehicle that admits light or air.",
    "door": "A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle.",
    "table": "A piece of furniture with a flat top supported by legs.",
    "chair": "A seat for one person, typically with a back and four legs.",
    "book": "A written or printed work consisting of pages glued or sewn together along one side and bound in covers.",
    "pen": "An instrument for writing or drawing with ink.",
    "pencil": "An instrument for writing or drawing, consisting of a thin stick of graphite or a similar substance enclosed in a wooden or metal case.",
    "paper": "Thin material produced by pressing together wet fibers of cellulose pulp derived from wood, rags, or grasses, and drying them into flexible sheets.",
    "cloud": "A visible mass of condensed water vapor floating in the atmosphere.",
    "rainbow": "A multicolored arc made by light striking water droplets.",
    "lightning": "A flash of bright light in the sky caused by an electrical discharge.",
    "thunder": "A loud rumbling or crashing noise heard after a lightning flash.",
    "star": "A fixed luminous point in the night sky that is a large, remote incandescent body like the sun.",
    "moon": "The natural satellite of the earth, visible (chiefly at night) by reflected light from the sun.",
    "sun": "The star around which the earth and other planets revolve.",
    "wind": "The perceptible natural movement of the air, especially in the form of a current of air blowing from a particular direction.",
    "snow": "Atmospheric water vapor frozen into ice crystals and falling in light white flakes or lying on the ground as a white layer.",
    "rain": "Moisture condensed from the atmosphere that falls visibly in separate drops.",
    "fire": "Combustion or burning, in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke.",
    "rock": "The solid mineral material forming part of the surface of the earth and other similar planets, exposed on the surface or underlying the soil.",
    "flower": "The part of a plant that is often brightly colored and has petals, or the type of plant that produces these.",
    "tree": "A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground.",
    "grass": "Vegetation consisting of typically short plants with long, narrow leaves growing wild or cultivated on lawns, pasture, and other land.",
    "stone": "Hard solid mineral matter of which rock is made, typically able to be shaped or split.",
    "metal": "A solid material that is typically hard, shiny, malleable, fusible, and ductile, with good electrical and thermal conductivity.",
    "plastic": "A synthetic material made from a wide range of organic polymers such as polyethylene, PVC, nylon, etc., that can be molded into shape while soft and then set into a rigid or slightly elastic form.",
    "glass": "A hard, brittle, transparent or translucent solid made by heating sand with soda and lime and then cooling it rapidly.",
    "fabric": "Cloth or other material produced by weaving or knitting textile fibers.",
    "leather": "A material made from the skin of an animal by tanning or a similar process.",
    "diamond": "A precious stone consisting of a clear and colorless crystalline form of pure carbon, the hardest naturally occurring substance.",
}

